service: GHM
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  apisapp:
    handler: handler.apiapp
    events:
      - http: ANY /{proxy+}
      - http: ANY /